---
- name: GoCD package repository (Debian)
  include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install server
  include_tasks: install-server.yml
  when: gocd_server

- name: Install agent
  include_tasks: install-agent.yml
  when: gocd_agent
