---
platforms:
  - name: ubuntu-18.04
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
