---
- name: Verify
  hosts: all
  vars:
    test_gocd_apt_key_url: https://download.gocd.org/GOCD-GPG-KEY.asc
    test_gocd_apt_repository: deb https://download.gocd.org /
    test_gocd_server_plugin_filename: docker-elastic-agents-3.0.0-245.jar
  tasks:
  - name: Test GoCD apt key
    block:
      - name: Get GoCD apt key status
        apt_key:
          url: "{{ test_gocd_apt_key_url }}"
          state: present
        check_mode: true
        register: test_gocd_apt_key_status

      - name: Test that GoCD apt key has been added
        assert:
          that:
            - not test_gocd_apt_key_status.changed
    when: ansible_os_family == 'Debian'

  - name: Test GoCD repository
    block:
      - name: Get GoCD repository status
        apt_repository:
          repo: "{{ test_gocd_apt_repository }}"
          state: present
        check_mode: true
        register: test_gocd_apt_repository_status

      - name: Test GoCD repository status
        assert:
          that:
            - not test_gocd_apt_repository_status.changed
    when: ansible_os_family == 'Debian'

  - name: Gather package facts
    package_facts:

  - name: GoCD Server
    block:
      - name: Test GoCD server package is installed
        assert:
          that:
            - "'go-server' in ansible_facts.packages"

      - name: Get GoCD server service state
        service:
          name: go-server
          state: started
          enabled: true
        check_mode: true
        register: test_gocd_server_service_state

      - name: Test GoCD server service state
        assert:
          that:
            - not test_gocd_server_service_state.changed

      - name: Get external plugin information
        stat:
          path: "/var/lib/go-server/plugins/external/{{ test_gocd_server_plugin_filename }}"
        register: test_gocd_server_external_plugin

      - name: Test GoCD external plugin installation
        assert:
          that:
            - test_gocd_server_external_plugin.stat.exists and test_gocd_server_external_plugin.stat.isreg

    when: "'gocd_servers' in group_names"

  - name: GoCD Agent
    block:
      - name: Test GoCD agent package is installed
        assert:
          that:
            - "'go-agent' in ansible_facts.packages"

      - name: Get GoCD agent service state
        service:
          name: go-agent
          state: started
          enabled: true
        check_mode: true
        register: test_gocd_agent_service_state

      - name: Test GoCD server service state
        assert:
          that:
            - not test_gocd_agent_service_state.changed
    when: "'gocd_agents' in group_names"
